
// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "./component/ui/utlity/NavBar";
import Footer from "./component/ui/utlity/Footer";
import ScrollToTopButton from "./component/ui/utlity/ScrollToTopButton";
import DashboardLayout from "./DashboardLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CURRENT_ROLE = "admin"; // change this to "admin" or "user"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAdmin = CURRENT_ROLE === "admin";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {isAdmin ? (
          // Admin Layout
          <DashboardLayout>
            <ScrollToTopButton />
            {children}
          </DashboardLayout>
        ) : (

          <>
            <NavBar />
            <ScrollToTopButton />
            {children}
            <Footer />
          </>
        )}
      </body>
    </html>
  );
}

